name: Child Workflow 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: echo "Child Workflow 3 - Step 3"

      # Add more steps/actions as needed
