name: Child Workflow 1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Child Workflow 1 - Step 1"

      # Add more steps/actions as needed
